apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tripviewer"
  namespace: oh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer 
    spec:
      containers:
        - name: "tripviewer"
          image: "registryvxd8656.azurecr.io/tripinsights/tripviewer:1.0"  
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: "tripviewer"
    labels:
        app: "tripviewer"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tripviewer"