apiVersion : apps/v1
kind: Deployment
metadata:
  name: "userprofile"
  namespace: oh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: "userprofile"
          image: "registryvxd8656.azurecr.io/tripinsights/userprofile:1.0"
          ports:
          - containerPort: 80
          env:
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: SQL_SERVER
              value: sqlservervxd8656.database.windows.net                   
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password     
---
apiVersion: v1
kind: Service
metadata:
    name: "userprofile"
    namespace: oh
    labels:
        app: "userprofile"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "userprofile"
